from models import Table

DIMENSIONS = {
    Table(
        table_name="countries",
        schema_name="public",
        target_table_name="public_countries",
        target_schema_name="public",
    ),
    Table(
        table_name="sites",
        schema_name="public",
        target_table_name="public_sites",
        target_schema_name="public",
    ),
    Table(
        table_name="fuel",
        schema_name="conversion_factors",
        target_table_name="conversion_factor_fuel",
        target_schema_name="public",
    ),
    Table(
        table_name="freight",
        schema_name="conversion_factors",
        target_table_name="conversion_factor_freight",
        target_schema_name="public",
    ),
    Table(
        table_name="metadata",
        schema_name="conversion_factors",
        target_table_name="conversion_factor_metadata",
        target_schema_name="public",
    ),
    Table(
        table_name="rate_sources",
        schema_name="conversion_factors",
        target_table_name="conversion_factor_rate_sources",
        target_schema_name="public",
    ),
    Table(
        table_name="rate_sources",
        schema_name="conversion_factors",
        target_table_name="conversion_factor_rate_sources",
        target_schema_name="public",
    ),
    Table(
        table_name="hotel_conversion_rates",
        schema_name="conversion_factors",
        target_table_name="conversion_factor_hotel_conversion_rates",
        target_schema_name="public",
    ),
    Table(
        table_name="electric_commercial_vehicles",
        schema_name="conversion_factors",
        target_table_name="conversion_factor_electric_commercial_vehicles",
        target_schema_name="public",
    ),
}
