FACTS_TABLE = {
    "ceoPay",
    "employeeTraining",
    "employeeTurnover",
    "financial",
    "governanceStandards",
    "humanRightsAssessment",
    "humanRightsRisks",
    "electricVehicles",
    "heavyVehicles",
    "waterUsage",
    "refridgerantUsage",
    "energyUsage",
    "sites",
    "minimumWageGuarantee",
    # "BOD",
    # "injuryRate",
    # "fuel",
    # "protectedAreas",
    # "corruptionTraining",
    # "passengerVehicles",
    # "corporateDebtSecurities",
    # "general",
    # "renewableEnergyProduction",
    # "electricityUsage",
    # "staffCommuting",
    # "emissionsToWater",
    # "hotels",
    # "ombudsman",
    # "employeeTraining",
    # "water",
    # "sbti",
    # "compensation",
    # "refrigerantUsage",
    # "highImpactClimateSectors",
    # "nonRenewableEnergyConsumption",
    "naturalGas",
    # "electricityUsage",
    # "humanRightsRiskAssessment",
    # "direct",
    # "employeeHiring",
    # "whistleblower",
    # "scopeThreeEmissions",
    # "minimumWageGuaranteeSchema",
    # "corruptionIncidents",
    # "fuelUsage",
    # "ESGriskAndOpportunity",
    # "purposeStatement",
    # "daysLostInjuries",
    # "consulatationProcess",
    # "averageBased",
    # "incomeStatements",
    # "realEstateEnergyEfficiency",
    # "catsAndDogs",
    # "fossilFuelSectorActivity",
    # "stakeholderEngagement",
    # "biodiversitySensitiveAreas",
    # "hazardousWaste",
    # "OECDGuidelinesMultinational",
    # "realEstateFossilFuels",
    "renewableEnergy",
    "airPollutants",
    "fuel",
}

FACTS_QUESTIONS = {
    "UNGCPrinciples",
    "employeeData",
    "fte",
    "revenue",
    "cSuiteDiversity",
    # "passengerVehicles",
    "controversialWeapons",
}

FACTS_DATAREQUEST = {"submission_attribute_calculations"}
